services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ferna
      POSTGRES_PASSWORD: 801372
      POSTGRES_DB: fitapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
